# tasks/dovecot.yml -- Install and configure Dovecot
---

- name: Install Dovecot
  package:
    name: "{{ item }}"
    state: installed
  with_items: "{{ mailserver_dovecot_packages }}"
  tags:
    - mailserver
    - dovecot

- name: Ensure Dovecot is started
  service:
    name: "{{ mailserver_dovecot_service }}"
    state: started
    enabled: true
  tags:
    - mailserver
    - dovecot

- name: Setting dovecot mail location
  template:
    src: 10-mail.conf.j2
    dest: /etc/dovecot/conf.d/10-mail.conf
  notify: restart dovecot
  tags:
    - mailserver
    - dovecot

- name: Applying thunderbird fix
  lineinfile:
    path: "{{ dovecot_config_dir }}/20-imap.conf"
    regexp: '^#imap_client_workarounds'
    line: 'imap_client_workarounds = tb-extra-mailbox-sep'
  notify: restart dovecot
  tags:
    - mailserver
    - dovecot

- name: Applying Outlook 2003 fix
  lineinfile:
    path: "{{ dovecot_config_dir }}/20-pop3.conf"
    regexp: '^#pop3_uidl_format'
    line: 'pop3_uidl_format = %08Xu%08Xv'
  notify: restart dovecot
  tags:
    - mailserver
    - dovecot

- name: Now configure Dovecot SASL for SMTP Auth
  template:
    src: 10-master.conf.j2
    dest: "{{ dovecot_config_dir }}/10-master.conf"
  notify: restart dovecot
  tags:
    - mailserver
    - dovecot

- name: Setting dovecot authentication mechanisms
  template:
    src: 10-auth.conf.j2
    dest: "{{ dovecot_config_dir }}/10-auth.conf"
  notify: restart dovecot
  tags:
    - mailserver
    - dovecot
